version: '3.9'

services:
  postgresql:
    restart: always
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=jooq_DB
      - POSTGRES_USER=xuser
      - POSTGRES_PASSWORD=password
