version: '3.9'

services:
  mysql:
    restart: always
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=jooq_DB
      - MYSQL_USER=xuser
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
