/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.db.autocreated;


import org.example.jooq.db.autocreated.tables.Airplane;
import org.example.jooq.db.autocreated.tables.Flight;
import org.example.jooq.db.autocreated.tables.Model;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in jooq_DB.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLIGHT_AIRPLANE = Internal.createIndex(DSL.name("airplane"), Flight.FLIGHT, new OrderField[] { Flight.FLIGHT.AIRPLANE }, false);
    public static final Index MODEL_COMPANY = Internal.createIndex(DSL.name("company"), Model.MODEL, new OrderField[] { Model.MODEL.COMPANY }, false);
    public static final Index AIRPLANE_MODEL = Internal.createIndex(DSL.name("model"), Airplane.AIRPLANE, new OrderField[] { Airplane.AIRPLANE.MODEL }, false);
    public static final Index FLIGHT_PASSENGER = Internal.createIndex(DSL.name("passenger"), Flight.FLIGHT, new OrderField[] { Flight.FLIGHT.PASSENGER }, false);
}
