/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.db.autocreated;


import java.util.Arrays;
import java.util.List;

import org.example.jooq.db.autocreated.tables.Airplane;
import org.example.jooq.db.autocreated.tables.Company;
import org.example.jooq.db.autocreated.tables.Databasechangelog;
import org.example.jooq.db.autocreated.tables.Databasechangeloglock;
import org.example.jooq.db.autocreated.tables.Flight;
import org.example.jooq.db.autocreated.tables.Model;
import org.example.jooq.db.autocreated.tables.Passenger;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>jooq_DB</code>
     */
    public static final JooqDb JOOQ_DB = new JooqDb();

    /**
     * The table <code>jooq_DB.airplane</code>.
     */
    public final Airplane AIRPLANE = Airplane.AIRPLANE;

    /**
     * The table <code>jooq_DB.company</code>.
     */
    public final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>jooq_DB.DATABASECHANGELOG</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>jooq_DB.DATABASECHANGELOGLOCK</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>jooq_DB.flight</code>.
     */
    public final Flight FLIGHT = Flight.FLIGHT;

    /**
     * The table <code>jooq_DB.model</code>.
     */
    public final Model MODEL = Model.MODEL;

    /**
     * The table <code>jooq_DB.passenger</code>.
     */
    public final Passenger PASSENGER = Passenger.PASSENGER;

    /**
     * No further instances allowed
     */
    private JooqDb() {
        super("jooq_DB", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Airplane.AIRPLANE,
            Company.COMPANY,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Flight.FLIGHT,
            Model.MODEL,
            Passenger.PASSENGER
        );
    }
}
