/*
 * This file is generated by jOOQ.
 */
package org.example.jooq.db.autocreated;


import org.example.jooq.db.autocreated.tables.Airplane;
import org.example.jooq.db.autocreated.tables.Company;
import org.example.jooq.db.autocreated.tables.Databasechangelog;
import org.example.jooq.db.autocreated.tables.Databasechangeloglock;
import org.example.jooq.db.autocreated.tables.Flight;
import org.example.jooq.db.autocreated.tables.Model;
import org.example.jooq.db.autocreated.tables.Passenger;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.airplane</code>.
     */
    public static final Airplane AIRPLANE = Airplane.AIRPLANE;

    /**
     * The table <code>public.company</code>.
     */
    public static final Company COMPANY = Company.COMPANY;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.flight</code>.
     */
    public static final Flight FLIGHT = Flight.FLIGHT;

    /**
     * The table <code>public.model</code>.
     */
    public static final Model MODEL = Model.MODEL;

    /**
     * The table <code>public.passenger</code>.
     */
    public static final Passenger PASSENGER = Passenger.PASSENGER;
}
